name: Contender
version: '${project.version}'
main: me.advait.contender.Contender
api-version: '1.21'
softdepend: [FastAsyncWorldEdit]
commands:
  duel:
    description: Open the duel setup menu
    permission: contender.master
    usage: /duel
  contender:
    description: Contender admin commands
    permission: contender.master
    usage: /contender <reload>
  endduel:
    description: End the duel you are currently in
    permission: contender.master
    usage: /endduel
  startvote:
    description: Start a community vote
    permission: contender.master
    usage: /startvote <seconds>
  endvote:
    description: End the current community vote
    permission: contender.master
    usage: /endvote
  vote:
    description: Open the voting GUI
    usage: /vote
permissions:
  contender.master:
    description: Allows access to duel management
    default: op
