#!/usr/bin/env python3
"""Extract vanilla sprite names (no textures) for dialog kit icons from a 26.2 client jar."""
import json
from pathlib import Path
import sys
import zipfile

with zipfile.ZipFile(sys.argv[1]) as client:
    files = set(client.namelist())
    def load(path):
        return json.loads(client.read(path)) if path in files else {}
    def textures(model, visited=()):
        if model in visited:
            return {}
        data = load('assets/minecraft/models/' + model.removeprefix('minecraft:') + '.json')
        result = textures(data['parent'], (*visited, model)) if 'parent' in data else {}
        result.update(data.get('textures', {}))
        return result
    def model_path(definition):
        if definition.get('type') == 'minecraft:model':
            return definition['model']
        # Choose the resting/default model, not a use animation or a special entity renderer.
        for key in ('on_false', 'fallback'):
            if key in definition:
                result = model_path(definition[key])
                if result:
                    return result
        return None
    def exists(sprite):
        return 'assets/minecraft/textures/' + sprite + '.png' in files
    aliases = {'clock': 'item/clock_09', 'compass': 'item/compass_18', 'recovery_compass': 'item/recovery_compass_18'}
    rows = {}
    for path in sorted(files):
        if not path.startswith('assets/minecraft/items/') or not path.endswith('.json'):
            continue
        item = path.removeprefix('assets/minecraft/items/').removesuffix('.json')
        candidates = [aliases.get(item, ''), 'item/' + item, 'block/' + item]
        model = model_path(load(path).get('model', {}))
        if model:
            tex = textures(model)
            for key in ('layer0', 'front', 'side', 'all', 'top', 'end', 'particle'):
                value = tex.get(key, '')
                if isinstance(value, dict):
                    value = value.get('sprite', '')
                seen = set()
                while value.startswith('#') and value not in seen:
                    seen.add(value)
                    value = tex.get(value[1:], '')
                    if isinstance(value, dict):
                        value = value.get('sprite', '')
                candidates.append(value.removeprefix('minecraft:'))
        for candidate in candidates:
            if candidate.startswith(('item/', 'block/')) and exists(candidate):
                rows[item] = candidate
                break
    target = Path(__file__).resolve().parents[1] / 'src/main/resources/item-sprites.properties'
    target.write_text('# Vanilla Minecraft 26.2 sprite names, generated by tools/generate_item_sprites.py.\n'
                      '# Entity-rendered items without a flat sprite use the dialog fallback.\n'
                      + ''.join(f'{key}={value}\n' for key, value in sorted(rows.items())))
    print(f'{len(rows)} verified sprite names -> {target}')
